### ISSUE TITLE
helm install zadig use version 1.2.0，can't pull image

### ISSUE THREAD

**Issue by HYmian** [koderover/zadig-doc#18]
Path: [zh_cn/02.安装与配置/03.helm.md](https://docs.koderover.com/zadig/install/helm-deploy/)

I use command:
`helm upgrade --install zadig --namespace zadig  koderover-chart/zadig --version=1.2.0 --set endpoint.FQDN=zadig.xxxxx.cn-hongkong.alicontainer.com --set tags.ingressController=false --set mongodb.persistence.storageClass=alicloud-disk-essd --set minio.persistence.storageClass=alicloud-disk-essd --set ingress-nginx.controller.ingressClass=nginx`
to install zadig, then encountered problem

Back-off pulling image "ccr.ccs.tencentyun.com/koderover-rc/aurora-api-proxy:20210706195803-164-main
Back-off pulling image "ccr.ccs.tencentyun.com/koderover-rc/hub-server:20210706195808-164-main-pr-52"
Back-off pulling image "ccr.ccs.tencentyun.com/koderover-rc/podexec:20210706195805-164-main-pr-52"

**Comment by jamsman94** [comment]
Did it recover later? No one else reported this problem and we made sure these images are available.

**Comment by HYmian** [comment]
ok，It's working fine now
