### ISSUE TITLE
想问下zadig-doc文档使用的什么wiki工具部署的

### ISSUE THREAD

**Issue by eryajf** [koderover/zadig-doc#2]
如题，感觉官方文档蛮好看的，不知道是使用什么主题部署的。

**Comment by leozhang2018** [comment]
> 如题，感觉官方文档蛮好看的，不知道是使用什么主题部署的。

We use [VuePress](https://vuepress.vuejs.org/) and theme [vdoing](https://github.com/xugaoyi/vuepress-theme-vdoing).
And modify the theme ourselves.

**Comment by eryajf** [comment]
> We use [VuePress](https://vuepress.vuejs.org/) and theme [vdoing](https://github.com/xugaoyi/vuepress-theme-vdoing).

Thank you, I also plan to use this theme to build your blog, you have changed very nice, I don't know if I will plan to share the theme package behind it.
