### ISSUE TITLE
基于k8s安装，没有升级脚本吗？

### ISSUE THREAD

**Issue by pan632660120** [koderover/zadig-doc#21]
Path: [zh_cn/02.安装与配置/02.install-on-k8s.md](https://docs.koderover.com/zadig/install/helm-deploy/)
好像官网给的安装脚本是1.0版本的？想升级只能卸载重装？

**Comment by jamsman94** [comment]
The script has been updated to v1.2.0 6days ago, check https://github.com/koderover/zadig/releases/tag/v1.2.0 for the latest installation script. And yes you can use the standard script to update the zadig system.
