### ISSUE TITLE
卸载脚本不存在了，

### ISSUE THREAD

**Issue by lesterhnu** [koderover/zadig-doc#28]
Path: [zh_cn/02.安装与配置/01.all-in-one.md](https://os.koderover.com/zadig/install/all-in-one/)
![image](https://user-images.githubusercontent.com/42615458/126921387-08438d26-3533-4028-832b-441243aef315.png)

![image](https://user-images.githubusercontent.com/42615458/126921365-ea5da918-a13a-41e9-8f96-c69f33d0104d.png)
![image](https://user-images.githubusercontent.com/42615458/126921406-f507cf44-404c-4492-a438-7b09b9df51a3.png)

**Comment by leozhang2018** [comment]
We have updated the installation documentation, please refer to the latest version. 
[https://docs.koderover.com](https://docs.koderover.com/zadig/install/all-in-one/#zadig-%E5%8D%B8%E8%BD%BD)
:)

**Comment by lesterhnu** [comment]
> We have updated the installation documentation, please refer to the latest version.
> [https://docs.koderover.com](https://docs.koderover.com/zadig/install/all-in-one/#zadig-%E5%8D%B8%E8%BD%BD)
> :)

ok,
