### ISSUE TITLE
what is the default account for the first login the zadig?

### ISSUE THREAD

**Issue by huminya76** [koderover/zadig-doc#7]
你好！
我是第一次装好zadig，然后登录的时候不知道输入什么账号登录进去，admin账号也没有密码？

Hello！
After the installation of zadig, I can not login zadig for the admin account ? I donot know what is the default account of the zadig?
Could you do me a help? Thanks a lot!

Path: [zh_cn/02.安装与配置/01.all-in-one.md](https://docs.koderover.com/zadig/install/all-in-one/)

**Comment by lilianzhu** [comment]
When you visit zadig for the first time , you should be able to access a registration page. Can you see this registration page?
![image](https://user-images.githubusercontent.com/11495272/122848361-f6ad0f00-d33b-11eb-89b2-38024a690eed.png)

If you can't see the page, maybe there's something wrong with the installation process. Can you provide a screenshot of the installation process? Or you can try to reinstall it  @huminya76

**Comment by huminya76** [comment]
Thanks for your help!&nbsp;
Today when I reviewed the log of installation,&nbsp; I found some errors including the next message:
&nbsp; &nbsp; NO ENCRYPTION KEY PROVIDED, ZADIG HAS GENERATED AN ENCRYPTION KEY
&nbsp; &nbsp; curl: (1) Protocol "https" not supported or disabled in libcurl
&nbsp; &nbsp; tar (child): /root/.koderover/helm/helm.tar.gz：无法 open: 没有那个文件或目录
&nbsp; &nbsp; tar (child): Error is not recoverable: exiting now
&nbsp; &nbsp; tar: Child returned status 2
&nbsp; &nbsp; tar: Error is not recoverable: exiting now
&nbsp; &nbsp; mv: 在"/root/.koderover/bin/helm" 后缺少了要操作的目标文件
&nbsp; &nbsp; Try 'mv --help' for more information.
&nbsp; &nbsp; chmod: 无法访问"/root/.koderover/bin/helm": 没有那个文件或目录
&nbsp; &nbsp; ./install_with_k8s.sh:行743: helm: 未找到命令
&nbsp; &nbsp; ./install_with_k8s.sh:行757: helm: 未找到命令
&nbsp; &nbsp; ./install_with_k8s.sh:行758: helm: 未找到命令
&nbsp; &nbsp; ./install_with_k8s.sh:行759: helm: 未找到命令



So I guess that the curl may not supported https protocol, and soon proved it. Curl 7.51.0 did not support https default.
After add https protocol to curl, I uninstalled zadig and reinstalled it. Then the full zadig appears and the registration page works!!!


GRATEFUL!


So my advice is the tips of https-supported to a new zadig user.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "koderover/zadig-doc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 上午9:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [koderover/zadig-doc] what is the default account for the first login the zadig? (#7)





 
When you visit zadig for the first time , you should be able to access a registration page. Can you see this registration page?
 
 
If you can't see the page, maybe there's something wrong with the installation process. Can you provide a screenshot of the installation process? Or you can try to reinstall it  @huminya76

**Comment by 27149chen** [comment]
@huminya76  please provide your os/kernel version details for further investigation

**Comment by huminya76** [comment]
***@***.*** ~]# cat /proc/version
Linux version 3.10.0-1160.el7.x86_64 ***@***.***) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-44) (GCC) ) #1 SMP Mon Oct 19 16:18:59 UTC 2020
***@***.*** ~]# uname -a
Linux localhost 3.10.0-1160.el7.x86_64 #1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux



installed by&nbsp;CentOS-7-x86_64-DVD-2009.iso


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "koderover/zadig-doc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月22日(星期二) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [koderover/zadig-doc] what is the default account for the first login the zadig? (#7)





 
@huminya76  please provide your os/kernel version details for further investigation
